#!/bin/sh
#
# If the ./configure script is missing, you can run this script to create it
#

if [ -n "$REZ_LIBTOOL_ROOT" ]; then
    ACLOCAL_OPTIONS="-I $REZ_LIBTOOL_ROOT/share/aclocal"
fi

libtoolize --force \
&& aclocal ${ACLOCAL_OPTIONS} \
&& automake --gnu --add-missing --copy \
&& autoconf

rm -rf autom4te.cache